<?php
/**
 * AuctionInformationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jetract
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JETRACT
 *
 * <b>Main API (Application Programming Interface) of Jetract E-Auction and E-Procurement solutions.</b><br><i>Property of INARTS YAZILIM BILISIM INSAAT SAN. VE TIC. A.Ş.</i>
 *
 * OpenAPI spec version: 0.9.4
 * Contact: support-api@jetract.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jetract;

/**
 * AuctionInformationResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AuctionInformationResponse
 * @package     Jetract
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuctionInformationResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuctionInformationResponse"
     */
    public function testAuctionInformationResponse()
    {
    }

    /**
     * Test attribute "iD"
     */
    public function testPropertyID()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "bidChangeLimit"
     */
    public function testPropertyBidChangeLimit()
    {
    }

    /**
     * Test attribute "bidLimit"
     */
    public function testPropertyBidLimit()
    {
    }

    /**
     * Test attribute "budget"
     */
    public function testPropertyBudget()
    {
    }

    /**
     * Test attribute "minimumChange"
     */
    public function testPropertyMinimumChange()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "visibleRank"
     */
    public function testPropertyVisibleRank()
    {
    }

    /**
     * Test attribute "listPrice"
     */
    public function testPropertyListPrice()
    {
    }

    /**
     * Test attribute "agreementText"
     */
    public function testPropertyAgreementText()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "deliveryDate"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "autoTimeExtension"
     */
    public function testPropertyAutoTimeExtension()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "defaultDuration"
     */
    public function testPropertyDefaultDuration()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "reminder"
     */
    public function testPropertyReminder()
    {
    }

    /**
     * Test attribute "publish"
     */
    public function testPropertyPublish()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "transportType"
     */
    public function testPropertyTransportType()
    {
    }

    /**
     * Test attribute "inviteMailTitle"
     */
    public function testPropertyInviteMailTitle()
    {
    }

    /**
     * Test attribute "inviteMailBody"
     */
    public function testPropertyInviteMailBody()
    {
    }

    /**
     * Test attribute "validUntilDate"
     */
    public function testPropertyValidUntilDate()
    {
    }

    /**
     * Test attribute "paymentTypeID"
     */
    public function testPropertyPaymentTypeID()
    {
    }

    /**
     * Test attribute "createdDate"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "approvalProcess"
     */
    public function testPropertyApprovalProcess()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "orderID"
     */
    public function testPropertyOrderID()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "timeControl"
     */
    public function testPropertyTimeControl()
    {
    }
}
