<?php
/**
 * AuctionNewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jetract
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JETRACT
 *
 * <b>Main API (Application Programming Interface) of Jetract E-Auction and E-Procurement solutions.</b><br><i>Property of INARTS YAZILIM BILISIM INSAAT SAN. VE TIC. A.Ş.</i>
 *
 * OpenAPI spec version: 0.9.4
 * Contact: support-api@jetract.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jetract;

/**
 * AuctionNewTest Class Doc Comment
 *
 * @category    Class
 * @description This model defines the required input for creating a new Auction.
 * @package     Jetract
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuctionNewTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuctionNew"
     */
    public function testAuctionNew()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "budget"
     */
    public function testPropertyBudget()
    {
    }

    /**
     * Test attribute "minimumChange"
     */
    public function testPropertyMinimumChange()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "agreementText"
     */
    public function testPropertyAgreementText()
    {
    }

    /**
     * Test attribute "deliveryRequired"
     */
    public function testPropertyDeliveryRequired()
    {
    }

    /**
     * Test attribute "deliveryDate"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "reminder"
     */
    public function testPropertyReminder()
    {
    }

    /**
     * Test attribute "publish"
     */
    public function testPropertyPublish()
    {
    }

    /**
     * Test attribute "listPrice"
     */
    public function testPropertyListPrice()
    {
    }

    /**
     * Test attribute "auctionItems"
     */
    public function testPropertyAuctionItems()
    {
    }

    /**
     * Test attribute "auctionConditions"
     */
    public function testPropertyAuctionConditions()
    {
    }

    /**
     * Test attribute "bidders"
     */
    public function testPropertyBidders()
    {
    }

    /**
     * Test attribute "bidderGroups"
     */
    public function testPropertyBidderGroups()
    {
    }

    /**
     * Test attribute "deliveryAddress"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "departmentID"
     */
    public function testPropertyDepartmentID()
    {
    }

    /**
     * Test attribute "autoTimeExtension"
     */
    public function testPropertyAutoTimeExtension()
    {
    }

    /**
     * Test attribute "bidChangeLimit"
     */
    public function testPropertyBidChangeLimit()
    {
    }

    /**
     * Test attribute "requestDeliveryDateForItems"
     */
    public function testPropertyRequestDeliveryDateForItems()
    {
    }

    /**
     * Test attribute "visibleOffers"
     */
    public function testPropertyVisibleOffers()
    {
    }

    /**
     * Test attribute "visibleRank"
     */
    public function testPropertyVisibleRank()
    {
    }

    /**
     * Test attribute "transportType"
     */
    public function testPropertyTransportType()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "validUntilDate"
     */
    public function testPropertyValidUntilDate()
    {
    }

    /**
     * Test attribute "bidLimit"
     */
    public function testPropertyBidLimit()
    {
    }

    /**
     * Test attribute "inviteMailBody"
     */
    public function testPropertyInviteMailBody()
    {
    }

    /**
     * Test attribute "inviteMailTitle"
     */
    public function testPropertyInviteMailTitle()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }
}
