<?php
/**
 * AuctionOfferItemResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JETRACT
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuctionOfferItemResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AuctionOfferItemResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuctionOfferItemResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuctionOfferItemResponse"
     */
    public function testAuctionOfferItemResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "offer_price"
     */
    public function testPropertyOfferPrice()
    {
    }

    /**
     * Test attribute "offer_discount"
     */
    public function testPropertyOfferDiscount()
    {
    }

    /**
     * Test attribute "offer_discount_type"
     */
    public function testPropertyOfferDiscountType()
    {
    }

    /**
     * Test attribute "approval_process_status"
     */
    public function testPropertyApprovalProcessStatus()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "offer_vat_rate"
     */
    public function testPropertyOfferVatRate()
    {
    }

    /**
     * Test attribute "offer_vat_price"
     */
    public function testPropertyOfferVatPrice()
    {
    }
}
