<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JETRACT
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for auctionsBiddersAgreementsResetAuctionIDPost
     *
     * .
     *
     */
    public function testAuctionsBiddersAgreementsResetAuctionIDPost()
    {
    }

    /**
     * Test case for bidderAuctionsAuctionIDGet
     *
     * .
     *
     */
    public function testBidderAuctionsAuctionIDGet()
    {
    }

    /**
     * Test case for bidderAuctionsGet
     *
     * .
     *
     */
    public function testBidderAuctionsGet()
    {
    }

    /**
     * Test case for biddersBiddingPost
     *
     * .
     *
     */
    public function testBiddersBiddingPost()
    {
    }

    /**
     * Test case for rootGet
     *
     * .
     *
     */
    public function testRootGet()
    {
    }
}
